spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://lb.internal:5306/huayi-health-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Huayi2021
      # 连接池配置
      initial-size: 5 # 初始化连接池时创建的连接数量
      min-idle: 5 # 最小空闲连接数
      max-active: 20 # 最大活跃连接数
      max-wait: 60000 # 获取连接时最大等待时间，单位毫秒

      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的SQL，要求是一个查询语句
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000ms

server:
  tomcat:
    max-swallow-size: -1 # 设置吞吐量大小限制

debug: false